;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.12
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :lsquic)



(cffi:defcfun ("gen_sockaddr" #.(lispify "gen_sockaddr" 'function)) :pointer
  (family :int)
  (ip :string)
  (port :pointer))


